# Generated by Django 5.2.1 on 2026-05-08 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('proceso', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'operadores',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('cantidad_lote', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='app.operador')),
            ],
            options={
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defectos', models.PositiveIntegerField(default=0, help_text='Cantidad de piezas con defecto en este análisis')),
                ('sin_defectos', models.PositiveIntegerField(default=0, help_text='Cantidad de piezas sin defecto en este análisis')),
                ('tipo_defectos', models.JSONField(default=list, help_text='Lista de nombres de defectos detectados, ej: ["hole", "Crease"]')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Timestamp de la validación, usado para reportes')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='app.lote')),
                ('operador', models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.PROTECT, related_name='validaciones', to='app.operador')),
            ],
            options={
                'db_table': 'validaciones',
            },
        ),
    ]
